export const tracks = [
  {
    id: 1,
    Title: "Chateau Gardens",
    Organization: "BBP Music Library",
    Bpm: "83bpm",
    Duration: "1:34",
    Release: "Introspection",
    Thumbnail: "",
    Url: "https://bbp-bbpmusiclibrary-tracks.s3.us-west-1.amazonaws.com/Chateau_Gardens.m3u8",
  },
  {
    id: 2,
    Title: "Escort",
    Organization: "BBP Music Library",
    Release: "Introspection",
    Bpm: "95bpm",
    Duration: "2:07",
    Thumbnail: "",
    Url: "https://bbp-bbpmusiclibrary-tracks.s3.us-west-1.amazonaws.com/Escort.m3u8",
  },
  {
    id: 3,
    Title: "Gobstoppers",
    Organization: "BBP Music Library",
    Bpm: "129bpm",
    Duration: "1:46",
    Release: "Introspection",
    Thumbnail: "",
    Url: "https://bbp-bbpmusiclibrary-tracks.s3.us-west-1.amazonaws.com/Gobstoppers.m3u8",
  },
  {
    id: 4,
    Title: "Hydroplane",
    Organization: "BBP Music Library",
    Bpm: "140bpm",
    Duration: "1:26",
    Release: "Introspection",
    Thumbnail: "",
    Url: "https://bbp-bbpmusiclibrary-tracks.s3.us-west-1.amazonaws.com/Hydroplane.m3u8",
  },
  {
    id: 5,
    Title: "Pinnacle",
    Organization: "BBP Music Library",
    Bpm: "140bpm",
    Duration: "2:08",
    Release: "Introspection",
    Thumbnail: "",
    Url: "https://bbp-bbpmusiclibrary-tracks.s3.us-west-1.amazonaws.com/Pinnacle.m3u8",
  },
];
